CREATE TABLE players(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL UNIQUE,
    high_score INT NOT NULL
);
CREATE TABLE games(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100),
    score INT NOT NULL
);
